<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/21/021
 * Time: 下午 4:58
 */

namespace app\api\controller\v1;


use app\common\service\SignAuth;
use app\common\service\SignHeaderAuth;
use think\Controller;

class Base extends Controller
{
   public function initialize()
   {
       $this->checkHeader();
       parent::initialize(); // TODO: Change the autogenerated stub
   }
    /**
     * 获取解密后的post的值
     * @return mixed
     * @throws \app\common\lib\exception\ApiException
     */
   protected function getPost(){
       $data = input('post.');
       SignAuth::validate($data);
       $post = SignAuth::decrypt($data['data']);
       return $post;
   }
    /**
     * @return bool
     * @throws \app\common\lib\exception\ApiException
     */
   protected function checkHeader(){
        $data = request()->header();

        SignHeaderAuth::validate($data);
        return true;
   }
}